<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1661317437103' stop='1661317437623'>
    <name>Login via Azure AD</name>
    <title>Login via Azure AD</title>
    <test-cases>
        <test-case start='1661317437115' status='broken' stop='1661317437621'>
            <name>Able to login via Azure AD</name>
            <title>Able to login via Azure AD</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='device' value='iPhone 13-15.5'/>
            </parameters>
            <steps>
                <step start='1661317437117' status='passed' stop='1661317437602'>
                    <name>Given James is at the app to login via Azure</name>
                    <title>Given James is at the app to login via Azure</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1661317437603' status='broken' stop='1661317437620'>
                    <name>When he provides email to sign in</name>
                    <title>When he provides email to sign in</title>
                    <attachments>
                        <attachment title='Data Table' source='c1e8472e-1462-43fc-a404-f3607e44d7a1-attachment.csv' type='text/csv' size='45'/>
                    </attachments>
                    <steps/>
                </step>
                <step start='1661317437621' status='canceled' stop='1661317437621'>
                    <name>Then he is able to access the app</name>
                    <title>Then he is able to access the app</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>TypeError: SigninPage_1.default.continue is not a function</message>
                <stack-trace>TypeError: SigninPage_1.default.continue is not a function
                    at World.&lt;anonymous> (/Users/a845751yara.com/poc/RNLogin/tests/src/step-definitions/azureADAuth.steps.ts:18:30)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                    at async wrapPromiseWithTimeout (/Users/a845751yara.com/poc/RNLogin/node_modules/@cucumber/cucumber/src/time.ts:56:10)
                    at async Object.run (/Users/a845751yara.com/poc/RNLogin/node_modules/@cucumber/cucumber/src/user_code_runner.ts:86:16)
                    at async Object.run (/Users/a845751yara.com/poc/RNLogin/node_modules/@cucumber/cucumber/src/runtime/step_runner.ts:50:20)
                    at async TestCaseRunner.invokeStep (/Users/a845751yara.com/poc/RNLogin/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:130:12)
                    at async TestCaseRunner.runStep (/Users/a845751yara.com/poc/RNLogin/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:312:20)
                    at async /Users/a845751yara.com/poc/RNLogin/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:214:36</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>